### ISSUE TITLE
Add different environment supports.

### ISSUE THREAD

**Issue by vikalpj** [Fueled/cookiecutter-angular#3]
We need support for all the environments like
- Dev Environment
- Staging Environment
- Production Environment

This can use something like https://www.npmjs.com/package/config or make use of environment variables to manage different environments and defaulting things to dev environment

**Comment by dope** [comment]
@vikalpj technically can close this as we covered this in omstars :)

**Comment by vikalpj** [comment]
@dope yeah after merging https://github.com/Fueled/cookiecutter-angular/pull/10 we will close this. :) thanks for reminding 👍

**Comment by vikalpj** [comment]
Merged with #10
